local harpoon = require("harpoon")
harpoon:setup()

vim.keymap.set("n", "<leader>a", function() harpoon:list():add() end, {desc="add file to harpoon"})
vim.keymap.set("n", "<C-e>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end, {desc="toggle harpoon ui"})

vim.keymap.set("n", "<leader>1", function() harpoon:list():select(1) end, {desc="open harpoon entry 1"})
vim.keymap.set("n", "<leader>2", function() harpoon:list():select(2) end, {desc="open harpoon entry 2"})
vim.keymap.set("n", "<leader>3", function() harpoon:list():select(3) end, {desc="open harpoon entry 3"})
vim.keymap.set("n", "<leader>4", function() harpoon:list():select(4) end, {desc="open harpoon entry 4"})
vim.keymap.set("n", "<leader>5", function() harpoon:list():select(5) end, {desc="open harpoon entry 5"})
vim.keymap.set("n", "<leader>6", function() harpoon:list():select(6) end, {desc="open harpoon entry 6"})
vim.keymap.set("n", "<leader>7", function() harpoon:list():select(7) end, {desc="open harpoon entry 7"})
vim.keymap.set("n", "<leader>8", function() harpoon:list():select(8) end, {desc="open harpoon entry 8"})
vim.keymap.set("n", "<leader>9", function() harpoon:list():select(9) end, {desc="open harpoon entry 9"})
vim.keymap.set("n", "<leader>0", function() harpoon:list():select(10) end, {desc="open harpoon entry 10"})
