vim.keymap.set('n', '<leader>jos', '<cmd>call jukit#splits#output()<CR>')
vim.keymap.set('n', '<leader>jts', '<cmd>call jukit#splits#term()<CR>')
vim.keymap.set('n', '<leader>js', '<cmd>call jukit#send#line()<CR>')
-- vim.keymap.set('v', '<leader>js', '<cmd>call jukit#send#selection()<CR>')
-- For the love of God I cannot get this to work through lua bindings. Time for vimscript directly from the docs
vim.cmd([[
vnoremap <leader>js :<C-U>call jukit#send#selection()<cr>
]])
vim.keymap.set('n', '<leader>j<space>', '<cmd>call jukit#send#section(0)<CR>')
vim.keymap.set('n', '<leader>jeuc', '<cmd>call jukit#send#until_current_section()<cr>')
vim.keymap.set('n', '<leader>jea', '<cmd>call jukit#send#all()<cr>')
vim.keymap.set('n', '<leader>jco', '<cmd>call jukit#cells#create_below(0)<CR>')
vim.keymap.set('n', '<leader>jcO', '<cmd>call jukit#cells#create_above(0)<CR>')
vim.keymap.set('n', '<leader>jct', '<cmd>call jukit#cells#create_below(1)<CR>')
vim.keymap.set('n', '<leader>jcT', '<cmd>call jukit#cells#create_above(1)<CR>')
vim.keymap.set('n', '<leader>jcd', '<cmd>call jukit#cells#delete()<CR>')
vim.keymap.set('n', '<leader>jcs', '<cmd>call jukit#cells#split()<CR>')
vim.keymap.set('n', '<leader>jcM', '<cmd>call jukit#cells#merge_above()<CR>')
vim.keymap.set('n', '<leader>jcm', '<cmd>call jukit#cells#merge_below()<CR>')
vim.keymap.set('n', '<leader>jck', '<cmd>call jukit#cells#move_up()<CR>zz')
vim.keymap.set('n', '<leader>jcj', '<cmd>call jukit#cells#move_down()<CR>zz')
vim.keymap.set('n', '<leader>jj', '<cmd>call jukit#cells#jump_to_next_cell()<CR>zz')
vim.keymap.set('n', '<leader>jk', '<cmd>call jukit#cells#jump_to_previous_cell()<CR>zz')
vim.keymap.set('n', '<leader>jcn', '<cmd>call jukit#convert#notebook_convert("jupyter-notebook")<CR>')
