vim.keymap.set('n', '<leader>jos', '<cmd>call jukit#splits#output()<CR>', {desc="open jukit repl in a split"})
vim.keymap.set('n', '<leader>jts', '<cmd>call jukit#splits#term()<CR>', {desc="open jukit in split with no command"})
vim.keymap.set('n', '<leader>js', '<cmd>call jukit#send#line()<CR>', {desc="send current line to repl (jukit)"})
-- vim.keymap.set('v', '<leader>js', '<cmd>call jukit#send#selection()<CR>')
-- For the love of God I cannot get this to work through lua bindings. Time for vimscript directly from the docs
vim.cmd([[
vnoremap <leader>js :<C-U>call jukit#send#selection()<cr> "guess no description for which-key L
]])
vim.keymap.set('n', '<leader>j<space>', '<cmd>call jukit#send#section(0)<CR>', {desc="send current cell to repl (jukit)"})
vim.keymap.set('n', '<leader>jeuc', '<cmd>call jukit#send#until_current_section()<cr>', {desc="send cell and all preceding cells to repl (jukit)"})
vim.keymap.set('n', '<leader>jea', '<cmd>call jukit#send#all()<cr>', {desc="send everything to repl (jukit)"})
vim.keymap.set('n', '<leader>jco', '<cmd>call jukit#cells#create_below(0)<CR>', {desc="create a cell below (jukit)"})
vim.keymap.set('n', '<leader>jcO', '<cmd>call jukit#cells#create_above(0)<CR>', {desc="create a cell above (jukit)"})
vim.keymap.set('n', '<leader>jct', '<cmd>call jukit#cells#create_below(1)<CR>', {desc="create a markdown cell below (jukit)"})
vim.keymap.set('n', '<leader>jcT', '<cmd>call jukit#cells#create_above(1)<CR>', {desc="create a markdown cell below (jukit)"})
vim.keymap.set('n', '<leader>jcd', '<cmd>call jukit#cells#delete()<CR>', {desc="delete cell (jukit)"})
vim.keymap.set('n', '<leader>jcs', '<cmd>call jukit#cells#split()<CR>', {desc="split cell at line above cursor (jukit)"})
vim.keymap.set('n', '<leader>jcM', '<cmd>call jukit#cells#merge_above()<CR>', {desc="merge cell with cell above (jukit)"})
vim.keymap.set('n', '<leader>jcm', '<cmd>call jukit#cells#merge_below()<CR>', {desc="merge cell with cell below (jukit)"})
vim.keymap.set('n', '<leader>jck', '<cmd>call jukit#cells#move_up()<CR>zz', {desc="move cell one cell up (jukit)"})
vim.keymap.set('n', '<leader>jcj', '<cmd>call jukit#cells#move_down()<CR>zz', {desc="move cell one cell down (jukit)"})
vim.keymap.set('n', '<leader>jj', '<cmd>call jukit#cells#jump_to_next_cell()<CR>zz', {desc="jump one cell down (jukit)"})
vim.keymap.set('n', '<leader>jk', '<cmd>call jukit#cells#jump_to_previous_cell()<CR>zz', {desc="jump one cell up (jukit)"})
vim.keymap.set('n', '<leader>jcn', '<cmd>call jukit#convert#notebook_convert("jupyter-notebook")<CR>', {desc="convert file between jupyter-notebook and jukit"})
